apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: klaus-mandola-poi-map-app-dev
  annotations:
    argocd/app-name: klaus-mandola-poi-map-app-dev
    backstage.io/kubernetes-id: klaus-mandola-poi-map-app
    backstage.io/kubernetes-namespace: klaus-mandola
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/klaus-mandola-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/klaus-mandola/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/klaus-mandola/deployments/klaus-mandola-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/klaus-mandola-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://klaus-mandola-poi-map-app-klaus-mandola.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/meiersheinz"
  system: workshop-system-klaus-mandola
  consumesApis:
    - gateway-api-klaus-mandola
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-klaus-mandola
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/meiersheinz"
